//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonnelProject
    {
        public int Id { get; set; }
        public string PersonnelId { get; set; }
        public int ProjectId { get; set; }
    
        public virtual Personnel Personnel { get; set; }
        public virtual Project Project { get; set; }
    }
}
