//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagement.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Personnel
    {
        public Personnel()
        {
            this.ProjectPersonnels = new HashSet<ProjectPersonnel>();
            this.Projects = new HashSet<Project>();
            this.Requirements = new HashSet<Requirement>();
        }
    
        public string Id { get; set; }
        public string Name { get; set; }
        public string Type { get; set; }
        public int TenantId { get; set; }
    
        public virtual Tenant Tenant { get; set; }
        public virtual ICollection<ProjectPersonnel> ProjectPersonnels { get; set; }
        public virtual ICollection<Project> Projects { get; set; }
        public virtual ICollection<Requirement> Requirements { get; set; }
    }
}
