CREATE TABLE [dbo].[PersonnelProjects]
(
	[Id] INT IDENTITY(1,1) NOT NULL PRIMARY KEY, 
    [PersonnelId] NVARCHAR(20) NOT NULL REFERENCES PERSONNEL(Id), 
    [ProjectId] INT NOT NULL REFERENCES PROJECTS(Id)
)
